modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"

[[mods]]
modId = "machinelib_testmod"
version = "0.0.0"
displayName = "MachineLib Test Mod"
description = '''Test mod for MachineLib (NeoForge).'''

[[dependencies.machinelib_testmod]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.machinelib_testmod]]
modId = "machinelib"
type = "required"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"
